- name: Set up NGINX on Fedora
  hosts: web
  become: true

  tasks:
    - name: Install NGINX
      dnf:
        name: nginx
        state: present

    - name: Copy index.html to web root
      copy:
        src: files/index.html
        dest: /usr/share/nginx/html/index.html
        owner: nginx
        group: nginx
        mode: '0644'

    - name: Enable and start NGINX
      service:
        name: nginx
        state: started
        enabled: true
